---
- name: Deploy Security Monitoring Script
  hosts: all
  become: true
  tasks:

    - name: Ensure required packages are installed
      package:
        name:
          - python3
          - tcpdump
        state: present

    - name: Copy security monitoring script to remote servers
      copy:
        src: security_monitor.py
        dest: /usr/local/bin/security_monitor.py
        mode: '0755'

    - name: Set up cron job for periodic execution
      cron:
        name: "Run Security Monitoring Script"
        job: "/usr/bin/python3 /usr/local/bin/security_monitor.py >> /var/log/security_monitor.log 2>&1"
        minute: "*/10"
